version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: avalia-filmes-api:latest
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
      - PORT=3333
      - MONGO_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - TMDB_URL=${TMDB_URL}
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
