openapi: 3.0.0
info:
  title: API de Avaliação de Filmes
  version: 1.0.0
  description: |
    Documentação dos endpoints disponíveis:
    - `/api/auth/signup`
    - `/api/auth/signin`
    - `/api/auth/forgot-password`
    - `/api/auth/reset-password/{token}`
    - `/api/v1/movies/genres`
    - `/api/v1/movies/discover`
    - `/api/v1/movies/{id}`
    - `/api/v1/movies/search`

servers:
  - url: http://localhost:3333
    description: Servidor local

paths:
  /api/auth/signup:
    post:
      summary: Registra um novo usuário
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserInput'
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  user:
                    type: object
        '409':
          description: Usuário já possui cadastro
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Usuário já possui cadastro"
        '500':
          description: Erro inesperado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Erro ao criar user"

  /api/auth/signin:
    post:
      summary: Faz login e retorna token JWT
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInInput'
      responses:
        '200':
          description: Autenticação bem-sucedida
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  token:
                    type: string
        '404':
          description: Usuário não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Usuário não encontrado"
        '400':
          description: Credenciais inválidas
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Senha incorreta"
        '500':
          description: Erro inesperado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Erro interno do servidor"
                    

  /api/auth/forgot-password:
    post:
      summary: Solicita recuperação de senha (envia e-mail com token)
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotPasswordInput'
      responses:
        '200':
          description: E-mail de recuperação enviado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Email enviado com sucesso"
        '404':
          description: Usuário não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Usuário não encontrado"
        '500':
          description: Erro inesperado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Erro interno do servidor"

  /api/auth/reset-password/{token}:
    post:
      summary: Reseta a senha usando token válido
      tags:
        - Auth
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
          description: Token recebido por e-mail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordInput'
      responses:
        '200':
          description: Senha alterada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Senha alterada com sucesso"
        '400':
          description: Token inválido ou expirado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Token não encontrado ou inválido"
        '500':
          description: Erro inesperado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Erro interno do servidor"

  /api/v1/movies/genres:
    get:
      summary: Lista gêneros de filmes (TMDb)
      tags:
        - Movies
      responses:
        '200':
          description: Lista de gêneros retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  genres:
                    type: array
                    items:
                      $ref: '#/components/schemas/Genre'
        '500':
          description: Erro interno ao buscar gêneros
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Erro ao buscar gêneros"

  /api/v1/movies/discover:
    get:
      summary: Descobre filmes por gênero e/ou ano
      tags:
        - Movies
      parameters:
        - in: query
          name: genre
          schema:
            type: integer
          description: ID do gênero (opcional)
        - in: query
          name: year
          schema:
            type: integer
          description: Ano de lançamento (opcional)
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Página de resultados (opcional
      responses:
        '200':
          description: Lista de filmes retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  genres:
                    type: array
                    items:
                      $ref: '#/components/schemas/MovieResponse'
        '500':
          description: Erro interno ao buscar filmes
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Erro ao buscar filmes"

  /api/v1/movies/{id}:
    get:
      summary: Retorna detalhes de um filme específico
      tags:
        - Movies
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID do filme no TMDb
      responses:
        '200':
          description: Detalhes do filme retornados com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  movie:
                    $ref: '#/components/schemas/MovieResponse'
        '404':
          description: Filme não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Filme não encontrado"
        '500':
          description: Erro interno ao obter detalhes do filme
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Erro interno do servidor"

  /api/v1/movies/search:
    get:
      summary: Busca filmes por texto
      tags:
        - Movies
      parameters:
        - in: query
          name: query
          required: true
          schema:
            type: string
          description: Termo de busca
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Página de resultados (opcional)
      responses:
        '200':
          description: Resultados da pesquisa retornados com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  movies:
                    type: array
                    items:
                      $ref: '#/components/schemas/MovieResponse'
        '500':
          description: Erro interno ao buscar filmes
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Erro interno do servidor ao buscar filmes"

components:
  schemas:
    CreateUserInput:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          minLength: 2
          example: João Silva
        email:
          type: string
          format: email
          example: joao@exemplo.com
        password:
          type: string
          minLength: 8
          format: password
          example: senha123

    SignInInput:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: joao@exemplo.com
        password:
          type: string
          minLength: 8
          format: password
          example: senha123

    ForgotPasswordInput:
      type: object
      required:
        - email
      properties:
        email:
          type: string
          format: email
          example: joao@exemplo.com

    ResetPasswordInput:
      type: object
      required:
        - password
      properties:
        password:
          type: string
          minLength: 8
          format: password
          example: novaSenha123

    Genre:
      type: object
      properties:
        id:
          type: integer
          example: 28
        name:
          type: string
          example: Ação

    MovieResponse:
      type: object
      properties:
        id:
          type: integer
          example: 550
        title:
          type: string
          example: Clube da Luta
        overview:
          type: string
          example: Um narrador insone encontra Tyler Durden...
        posterUrl:
          type: string
          nullable: true
          example: https://image.tmdb.org/t/p/w500/a26cQPRhJPX6GbWfQbvZdrrp9j9.jpg
        backdropUrl:
          type: string
          nullable: true
          example: https://image.tmdb.org/t/p/w500/path/to/backdrop.jpg
        genres:
          type: array
          items:
            type: string
            example: Drama
        releaseDate:
          type: string
          example: 1999-10-15
        runtime:
          type: integer
          nullable: true
          example: 139







